/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'channel_exists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'cleanup_expired_sessions' : IDL.Func([], [], []),
  'create_channel' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'generate_experience' : IDL.Func([IDL.Text], [IDL.Text], []),
  'get_messages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], []),
  'poll_veil' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'channelCode' : IDL.Text, 'phase' : IDL.Text })],
      [],
    ),
  'send_message' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'submit_veil_hash' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'token' : IDL.Text, 'signal' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'veil_consent' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'channel_exists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'cleanup_expired_sessions' : IDL.Func([], [], []),
    'create_channel' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'generate_experience' : IDL.Func([IDL.Text], [IDL.Text], []),
    'get_messages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], []),
    'poll_veil' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'channelCode' : IDL.Text, 'phase' : IDL.Text })],
        [],
      ),
    'send_message' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'submit_veil_hash' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'token' : IDL.Text, 'signal' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'veil_consent' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };