/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : string,
  'text' : string,
  'timestamp' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'channel_exists' : ActorMethod<[string], boolean>,
  'cleanup_expired_sessions' : ActorMethod<[], undefined>,
  'create_channel' : ActorMethod<[string], boolean>,
  'generate_experience' : ActorMethod<[string], string>,
  'get_messages' : ActorMethod<[string], Array<Message>>,
  'poll_veil' : ActorMethod<
    [string],
    { 'channelCode' : string, 'phase' : string }
  >,
  'send_message' : ActorMethod<[string, string], boolean>,
  'submit_veil_hash' : ActorMethod<
    [string, string],
    { 'token' : string, 'signal' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'veil_consent' : ActorMethod<[string, boolean], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];